import React from "react";
import {
  Create,
  SimpleForm,
  TextInput,
  SelectInput,
  Toolbar,
  SaveButton,
  useDataProvider,
  useRedirect,
  useNotify,
} from "react-admin";
import { useFormContext, useWatch } from "react-hook-form";
import { 
  Box, 
  Paper, 
  Typography, 
  Divider, 
  Chip,
  Alert,
  Stack,
  useTheme,
  useMediaQuery,
  alpha,
} from "@mui/material";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ErrorIcon from "@mui/icons-material/Error";
import InfoIcon from "@mui/icons-material/Info";
import RichTextInput from "../../components/RichTextInput/RichTextInput";
import slugify from "../../utils/slugify";

const statusChoices = [
  { id: "draft", name: "Draft" },
  { id: "published", name: "Published" },
];

const validateRequired = (v: any) => (v ? undefined : "Required");

// Custom toolbar component with enhanced styling
const CustomToolbar = (toolbarProps: any) => {
  return (
    <Toolbar 
      {...toolbarProps}
      sx={{
        backgroundColor: 'background.paper',
        borderTop: '1px solid',
        borderColor: 'divider',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        p: 2,
        gap: 2,
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <InfoIcon sx={{ fontSize: 20, color: 'info.main' }} />
        <Typography variant="body2" color="text.secondary">
          Fill in all required fields to save
        </Typography>
      </Box>
      <SaveButton 
        mutationOptions={{
          onSuccess: () => {
            // Will use the redirect from Create component
          }
        }}
        sx={{
          borderRadius: 2,
          px: 3,
          fontWeight: 600,
        }}
      />
    </Toolbar>
  );
};

const PagesCreate: React.FC = (props) => {
  const dataProvider = useDataProvider();

  // async validator factory for slug uniqueness
  const makeValidateSlug = () => async (value: string) => {
    if (!value) return "Required";
    try {
      // Try API-side filtering first (if backend supports it)
      const res = await dataProvider.getList("pages", {
        pagination: { page: 1, perPage: 1000 },
        sort: { field: "id", order: "ASC" },
        filter: { slug: value },
      });
      const list = Array.isArray((res as any).data) ? (res as any).data : [];
      // Fallback: client-side filter if backend ignores slug filter
      const exists = list.some((p: any) => p?.slug === value);
      if (exists) return "This slug is already in use";
      return undefined;
    } catch (err) {
      console.warn("Slug uniqueness check failed", err);
      try {
        // Final fallback: fetch without filters and check locally
        const res = await dataProvider.getList("pages", {
          pagination: { page: 1, perPage: 1000 },
          sort: { field: "id", order: "ASC" },
          filter: {},
        });
        const list = Array.isArray((res as any).data) ? (res as any).data : [];
        const exists = list.some((p: any) => p?.slug === value);
        if (exists) return "This slug is already in use";
      } catch {}
      return undefined;
    }
  };

  // Component to auto-generate slug from title
  const SlugInput: React.FC = () => {
    const { setValue } = useFormContext();
    const title = useWatch({ name: "title" });
    const slug = useWatch({ name: "slug" });
    const [isAutoGenerated, setIsAutoGenerated] = React.useState(true);
    const [slugStatus, setSlugStatus] = React.useState<'idle' | 'checking' | 'valid' | 'invalid'>('idle');

    React.useEffect(() => {
      // Only auto-generate if slug is empty (not manually edited)
      if (title && isAutoGenerated) {
        const newSlug = slugify(title);
        setValue("slug", newSlug);
      }
    }, [title, isAutoGenerated, setValue]);

    // Check slug validity with debounce
    React.useEffect(() => {
      if (slug && slug.length > 0) {
        setSlugStatus('checking');
        const timer = setTimeout(async () => {
          try {
            const res = await dataProvider.getList("pages", {
              pagination: { page: 1, perPage: 1000 },
              sort: { field: "id", order: "ASC" },
              filter: { slug },
            });
            const list = Array.isArray((res as any).data) ? (res as any).data : [];
            const exists = list.some((p: any) => p?.slug === slug);
            setSlugStatus(exists ? 'invalid' : 'valid');
          } catch (err) {
            console.warn('Slug check failed:', err);
            setSlugStatus('idle');
          }
        }, 800); // Increased debounce to 800ms to reduce API calls
        return () => clearTimeout(timer);
      } else {
        setSlugStatus('idle');
      }
    }, [slug]);

    return (
      <Box>
        <TextInput
          source="slug"
          label="Slug"
          helperText="Auto-generated from title, or enter manually for custom URL"
          validate={makeValidateSlug()}
          fullWidth
          onChange={() => setIsAutoGenerated(false)}
          sx={{
            '& .MuiOutlinedInput-root': {
              borderRadius: 2,
            },
          }}
        />
        {slug && slugStatus !== 'idle' && slugStatus !== 'checking' && (
          <Box sx={{ mt: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
            {slugStatus === 'valid' ? (
              <>
                <CheckCircleIcon sx={{ fontSize: 18, color: 'success.main' }} />
                <Typography variant="caption" color="success.main" fontWeight={600}>
                  Slug is available
                </Typography>
              </>
            ) : (
              <>
                <ErrorIcon sx={{ fontSize: 18, color: 'error.main' }} />
                <Typography variant="caption" color="error.main" fontWeight={600}>
                  Slug already in use
                </Typography>
              </>
            )}
          </Box>
        )}
      </Box>
    );
  };

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const redirect = useRedirect();
  const notify = useNotify();

  const onSuccess = () => {
    notify('Page created successfully', { type: 'success' });
    redirect('list', 'pages');
  };

  return (
    <Create 
      {...props} 
      redirect="list"
      mutationOptions={{ onSuccess }}
    >
      <Box sx={{ maxWidth: 1200, mx: 'auto', p: { xs: 2, sm: 3 } }}>
        {/* Header Section */}
        <Paper
          elevation={0}
          sx={{
            p: { xs: 2.5, sm: 3 },
            mb: 3,
            borderRadius: 2,
            border: '1px solid',
            borderColor: 'divider',
            backgroundColor: alpha(theme.palette.primary.main, 0.04),
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
            <Typography variant={isMobile ? "h5" : "h4"} fontWeight={700} color="primary.main">
              Create New Page
            </Typography>
            <Chip
              label="New"
              color="primary"
              size="small"
              sx={{
                fontWeight: 700,
                height: 28,
              }}
            />
          </Box>
          <Typography variant="body2" color="text.secondary">
            Create a new page with rich content. Your page will be accessible via its unique slug URL.
          </Typography>
        </Paper>

        {/* Info Alert */}
        <Alert 
          severity="info" 
          icon={<InfoIcon />}
          sx={{ 
            mb: 3,
            borderRadius: 2,
            '& .MuiAlert-message': {
              width: '100%',
            },
          }}
        >
          <Typography variant="body2" fontWeight={600} gutterBottom>
            Quick Tips
          </Typography>
          <Typography variant="caption" component="div">
            • The slug is auto-generated from the title but can be customized
            <br />
            • Save as draft to continue editing later
            <br />
            • Publish when ready to make the page publicly visible
          </Typography>
        </Alert>

        {/* Main Form */}
        <Paper
          elevation={0}
          sx={{
            borderRadius: 2,
            overflow: 'hidden',
            border: '1px solid',
            borderColor: 'divider',
          }}
        >
          <SimpleForm 
            toolbar={<CustomToolbar />}
            sx={{
              '& .RaSimpleFormIterator-form': {
                padding: 0,
              },
            }}
          >
            {/* Basic Information Section */}
            <Box sx={{ p: { xs: 2, sm: 3 }, width: '100%' }}>
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight={700} gutterBottom color="text.primary">
                  Basic Information
                </Typography>
                <Divider sx={{ mb: 3 }} />

                <Stack spacing={3}>
                  <TextInput 
                    source="title" 
                    label="Page Title" 
                    validate={validateRequired} 
                    fullWidth
                    helperText="Enter a descriptive title for your page"
                    sx={{
                      '& .MuiOutlinedInput-root': {
                        borderRadius: 2,
                      },
                    }}
                  />
                  
                  <SlugInput />
                  
                  <Box>
                    <SelectInput 
                      source="status" 
                      choices={statusChoices} 
                      defaultValue="draft"
                      fullWidth
                      helperText="Draft pages are not visible to the public"
                      sx={{
                        '& .MuiOutlinedInput-root': {
                          borderRadius: 2,
                        },
                      }}
                    />
                  </Box>
                </Stack>
              </Box>

              {/* Content Section */}
              <Box>
                <Typography variant="h6" fontWeight={700} gutterBottom color="text.primary">
                  Page Content
                </Typography>
                <Divider sx={{ mb: 3 }} />
                
                <RichTextInput 
                  source="content" 
                  label="Content" 
                  validate={validateRequired} 
                  fullWidth 
                />
              </Box>
            </Box>
          </SimpleForm>
        </Paper>

        {/* Footer Info */}
        <Box 
          sx={{ 
            mt: 3, 
            p: 2,
            textAlign: 'center',
            borderTop: '1px solid',
            borderColor: 'divider',
          }}
        >
          <Typography variant="caption" color="text.secondary">
            After saving, you can preview your page or continue editing from the pages list
          </Typography>
        </Box>
      </Box>
    </Create>
  );
};

export default PagesCreate;
