import React from "react";
import { TextInput, useDataProvider } from "react-admin";
import { useFormContext, useWatch } from "react-hook-form";
import { Box, Typography } from "@mui/material";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ErrorIcon from "@mui/icons-material/Error";
import slugify from "../../utils/slugify"; 

const SlugInputWithValidation: React.FC = () => {
  const dataProvider = useDataProvider();
  const { setValue } = useFormContext();
  const title = useWatch({ name: "title" });
  const slug = useWatch({ name: "slug" });
  
  const [isAutoGenerated, setIsAutoGenerated] = React.useState(true);
  const [slugStatus, setSlugStatus] = React.useState<'idle' | 'checking' | 'valid' | 'invalid'>('idle');

  // --- Async Slug Uniqueness Validator (For Form Submission) ---
  const validateSlug = async (value: string) => {
    if (!value) return "Required";
    try {
      const res = await dataProvider.getList("pages", {
        pagination: { page: 1, perPage: 1000 },
        sort: { field: "id", order: "ASC" },
        filter: { slug: value },
      });
      const list = Array.isArray((res as any).data) ? (res as any).data : [];
      const exists = list.some((p: any) => p?.slug === value);
      if (exists) return "This slug is already in use";
      return undefined;
    } catch (err) {
      // Allow saving if API check fails, but log warning
      console.warn("Slug uniqueness check failed during validation:", err);
      return undefined; 
    }
  };

  // --- Auto-Generation Logic ---
  React.useEffect(() => {
    if (title && isAutoGenerated) {
      const newSlug = slugify(title);
      setValue("slug", newSlug, { shouldValidate: true });
    }
  }, [title, isAutoGenerated, setValue]);

  // --- Debounced Status Check Logic (For Live Feedback) ---
  React.useEffect(() => {
    if (slug && slug.length > 0) {
      setSlugStatus('checking');
      const timer = setTimeout(async () => {
        try {
          const res = await dataProvider.getList("pages", {
            pagination: { page: 1, perPage: 1000 },
            sort: { field: "id", order: "ASC" },
            filter: { slug },
          });
          const list = Array.isArray((res as any).data) ? (res as any).data : [];
          const exists = list.some((p: any) => p?.slug === slug);
          setSlugStatus(exists ? 'invalid' : 'valid');
        } catch (err) {
          console.warn('Slug live check failed:', err);
          setSlugStatus('idle'); // Revert to idle if check fails
        }
      }, 800);
      return () => clearTimeout(timer);
    } else {
      setSlugStatus('idle');
    }
  }, [slug, dataProvider]);

  return (
    <Box>
      <TextInput
        source="slug"
        label="Slug"
        helperText="Auto-generated from title, or enter manually for custom URL"
        validate={validateSlug}
        fullWidth
        onChange={() => setIsAutoGenerated(false)} // User manually edited
        sx={{
          '& .MuiOutlinedInput-root': {
            borderRadius: 2,
          },
        }}
      />
      {/* Live Feedback UI */}
      {slug && slugStatus !== 'idle' && slugStatus !== 'checking' && (
        <Box sx={{ mt: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
          {slugStatus === 'valid' ? (
            <>
              <CheckCircleIcon sx={{ fontSize: 18, color: 'success.main' }} />
              <Typography variant="caption" color="success.main" fontWeight={600}>
                Slug is available
              </Typography>
            </>
          ) : (
            <>
              <ErrorIcon sx={{ fontSize: 18, color: 'error.main' }} />
              <Typography variant="caption" color="error.main" fontWeight={600}>
                Slug already in use
              </Typography>
            </>
          )}
        </Box>
      )}
    </Box>
  );
};

export default SlugInputWithValidation;